(()=>{
const style=document.createElement('style');style.textContent=`
#home .stats-grid{display:none!important}.proDash{margin-top:16px}.proHero{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.proCard{border-radius:18px;padding:20px;color:#fff;min-height:130px;position:relative;overflow:hidden;box-shadow:0 12px 28px rgba(40,25,22,.12)}.proCard:after{content:'';position:absolute;width:130px;height:130px;border:22px solid rgba(255,255,255,.09);border-radius:30px;left:-45px;bottom:-60px;transform:rotate(25deg)}.proCard small{display:block;opacity:.85;font-size:12px}.proCard b{display:block;font-size:31px;margin-top:14px;direction:ltr;text-align:right}.pcGold{background:linear-gradient(135deg,#d99b12,#f2bd35);color:#20160b}.pcGreen{background:linear-gradient(135deg,#087a4a,#11a866)}.pcDark{background:linear-gradient(135deg,#211817,#4a302c)}.proStats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:14px}.miniStat{background:#fff;border:1px solid #e9e2dd;border-radius:16px;padding:17px;box-shadow:0 8px 24px rgba(51,31,28,.06);border-top:4px solid var(--c)}.miniStat span{font-size:12px;color:#756a66}.miniStat b{display:block;font-size:27px;margin-top:8px}.miniStat em{display:block;font-style:normal;font-size:11px;color:#948985;margin-top:5px}.proCharts{display:grid;grid-template-columns:1.15fr .85fr;gap:14px;margin-top:14px}.chartCard{background:#fff;border:1px solid #e9e2dd;border-radius:18px;padding:20px;box-shadow:0 8px 24px rgba(51,31,28,.06)}.chartCard h3{margin:0 0 18px;font-size:17px}.donutWrap{display:flex;align-items:center;justify-content:center;gap:25px;min-height:220px}.donut{width:170px;height:170px;border-radius:50%;position:relative}.donut:after{content:'';position:absolute;inset:34px;background:#fff;border-radius:50%}.donutCenter{position:absolute;inset:0;display:grid;place-content:center;text-align:center;z-index:2;font-weight:800}.donutCenter b{font-size:25px}.legend{display:grid;gap:10px}.legend div{display:flex;align-items:center;gap:8px;font-size:12px}.dot{width:10px;height:10px;border-radius:50%}.bars{display:grid;gap:14px}.barLine{display:grid;grid-template-columns:100px 1fr 60px;align-items:center;gap:10px;font-size:12px}.barTrack{height:13px;background:#f0ebe8;border-radius:99px;overflow:hidden}.barFill{height:100%;border-radius:99px}.proNote{margin-top:12px;padding:11px 14px;border-radius:12px;background:#fff7df;color:#76510a;font-size:12px}.proLoading{padding:25px;text-align:center;color:#7b716d}.actions{margin-top:14px!important}@media(max-width:950px){.proHero{grid-template-columns:1fr}.proStats{grid-template-columns:repeat(2,1fr)}.proCharts{grid-template-columns:1fr}}@media(max-width:650px){.proStats{grid-template-columns:1fr 1fr}.proCard b{font-size:25px}.donutWrap{flex-direction:column}.barLine{grid-template-columns:78px 1fr 50px}}
`;document.head.appendChild(style);
const home=document.getElementById('home'),filters=home?.querySelector('.filters');if(!home||!filters)return;const box=document.createElement('div');box.id='proDashboard';box.className='proDash';box.innerHTML='<div class="proLoading">جاري حساب إحصائيات Ozon والطلبات...</div>';filters.after(box);
const parcel=x=>Array.isArray(x?.ozon_parcels)?x.ozon_parcels[0]:(x?.ozon_parcels||null),num=v=>Number(v||0),fmt=v=>num(v).toLocaleString('fr-MA',{maximumFractionDigits:2}),norm=s=>String(s||'').toLowerCase(),isDelivered=s=>norm(s).includes('livr')||norm(s).includes('deliver'),isReturn=s=>norm(s).includes('retour')||norm(s).includes('return'),isRefused=s=>norm(s).includes('refus'),isProgress=s=>!isDelivered(s)&&!isReturn(s)&&!isRefused(s);
async function allOrders(){let out=[],page=1,total=1;do{const j=await api(`orders?page=${page}&limit=100`);out.push(...(j.data||[]));total=Math.max(1,Math.ceil(Number(j.count||out.length)/100));page++}while(page<=total&&page<=100);return out}
function status(x){const p=parcel(x);return p?.ozon_status_label||p?.ozon_status||x.status||''}
function today(d){if(!d)return false;const a=new Date(d),b=new Date();return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function render(rows){const sent=rows.filter(x=>parcel(x)?.tracking_number),del=sent.filter(x=>isDelivered(status(x))),ret=sent.filter(x=>isReturn(status(x))),ref=sent.filter(x=>isRefused(status(x))),prog=sent.filter(x=>isProgress(status(x))),unsent=rows.filter(x=>!parcel(x)?.tracking_number),delCOD=del.reduce((a,x)=>a+num(x.cod_total),0),totalCOD=rows.reduce((a,x)=>a+num(x.cod_total),0),todayCreated=rows.filter(x=>today(x.created_at)),todayDel=del.filter(x=>today(parcel(x)?.updated_at||parcel(x)?.status_updated_at||x.updated_at)),rate=sent.length?del.length/sent.length*100:0;const parts=[del.length,prog.length,ret.length+ref.length],sum=Math.max(1,parts.reduce((a,b)=>a+b,0)),p1=parts[0]/sum*100,p2=p1+parts[1]/sum*100;
box.innerHTML=`<div class="proHero"><div class="proCard pcGold"><small>المبلغ المستحق من Ozon حسب الطلبات Livré</small><b>${fmt(delCOD)} DH</b><small>${del.length} طلبية مسلمة</small></div><div class="proCard pcGreen"><small>Taux de livraison</small><b>${rate.toFixed(1)}%</b><small>${del.length} Livré من ${sent.length} مرسلة لـ Ozon</small></div><div class="proCard pcDark"><small>إجمالي COD فالسيستيم</small><b>${fmt(totalCOD)} DH</b><small>${rows.length} طلبية</small></div></div>
<div class="proStats"><div class="miniStat" style="--c:#19764b"><span>تسلمات اليوم</span><b>${todayDel.length}</b><em>طلبات ولات Livré اليوم حسب آخر تحديث متوفر</em></div><div class="miniStat" style="--c:#d59a24"><span>En cours</span><b>${prog.length}</b><em>مرسلة لـ Ozon ومازال ما تسلماتش</em></div><div class="miniStat" style="--c:#c54d4d"><span>Retourné</span><b>${ret.length}</b><em>طلبات راجعة</em></div><div class="miniStat" style="--c:#8e3434"><span>Refusé</span><b>${ref.length}</b><em>طلبات مرفوضة</em></div><div class="miniStat" style="--c:#5a4a9d"><span>طلبات اليوم</span><b>${todayCreated.length}</b><em>تسجلات اليوم فالسيستيم</em></div><div class="miniStat" style="--c:#277aa6"><span>مرسلة لـ Ozon</span><b>${sent.length}</b><em>عندها Tracking</em></div><div class="miniStat" style="--c:#8c7b72"><span>مازال ما تصيفطاتش</span><b>${unsent.length}</b><em>بلا Tracking Ozon</em></div><div class="miniStat" style="--c:#15945c"><span>COD Livré</span><b>${fmt(delCOD)} DH</b><em>قيمة الطلبات المسلمة</em></div></div>
<div class="proCharts"><div class="chartCard"><h3>Statistiques Colis</h3><div class="bars">${[['Livré',del.length,'#15945c'],['En cours',prog.length,'#d59a24'],['Retourné',ret.length,'#c54d4d'],['Refusé',ref.length,'#8e3434'],['Non envoyé',unsent.length,'#7e6f68']].map(([n,v,c])=>`<div class="barLine"><b>${n}</b><div class="barTrack"><div class="barFill" style="width:${rows.length?Math.max(1,v/rows.length*100):0}%;background:${c}"></div></div><strong>${v}</strong></div>`).join('')}</div></div><div class="chartCard"><h3>% حالة الشحنات</h3><div class="donutWrap"><div class="donut" style="background:conic-gradient(#15945c 0 ${p1}%,#d59a24 ${p1}% ${p2}%,#c54d4d ${p2}% 100%)"><div class="donutCenter"><b>${rate.toFixed(0)}%</b><small>Livré</small></div></div><div class="legend"><div><i class="dot" style="background:#15945c"></i>Livré: ${del.length}</div><div><i class="dot" style="background:#d59a24"></i>En cours: ${prog.length}</div><div><i class="dot" style="background:#c54d4d"></i>Retour/Refus: ${ret.length+ref.length}</div></div></div></div></div><div class="proNote">ملاحظة: “المستحق من Ozon” محسوب حالياً من COD ديال الطلبات Livré. باش نطلع بالضبط شحال Ozon خلصك وشحال باقي عليه خاصنا نربط بيانات الفوترة/التعويضات ديال Ozon كذلك.</div>`}
async function load(){try{render(await allOrders())}catch(e){box.innerHTML=`<div class="msg err">تعذر تحميل الإحصائيات المتقدمة: ${String(e.message||e)}</div>`}}
setTimeout(load,300);document.querySelector('.nav[data-view="home"]')?.addEventListener('click',()=>setTimeout(load,150));window.EBRefreshProDashboard=load;
})();