(()=>{const FN=()=>EB.SUPABASE_URL+'/functions/v1/elegance-ops';
const style=document.createElement('style');style.textContent=`
#home .stats-grid{display:none!important}.proDash{margin-top:16px}.proHero{display:grid;grid-template-columns:1.2fr .9fr .9fr;gap:14px}.proCard{border-radius:22px;padding:22px;min-height:142px;position:relative;overflow:hidden;border:1px solid #e8e0db;box-shadow:0 12px 32px rgba(36,24,20,.08)}.proCard small{display:block;font-size:12px;opacity:.8}.proCard b{display:block;font-size:32px;margin:14px 0 5px;direction:ltr;text-align:right}.pcDue{background:linear-gradient(135deg,#ffd95a,#f2b934);color:#21180d}.pcPaid{background:linear-gradient(135deg,#092b25,#124e42);color:white}.pcCA{background:linear-gradient(135deg,#fdfdfc,#f0ece9);color:#201817}.proStats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:14px}.miniStat{background:#fff;border:1px solid #e9e2dd;border-radius:18px;padding:17px;box-shadow:0 7px 22px rgba(51,31,28,.05);border-top:4px solid var(--c)}.miniStat span{font-size:12px;color:#756a66}.miniStat b{display:block;font-size:27px;margin-top:7px}.miniStat em{display:block;font-style:normal;font-size:11px;color:#948985;margin-top:5px}.proCharts{display:grid;grid-template-columns:1.2fr .8fr;gap:14px;margin-top:14px}.chartCard{background:#fff;border:1px solid #e9e2dd;border-radius:20px;padding:20px;box-shadow:0 8px 24px rgba(51,31,28,.05)}.chartCard h3{margin:0 0 18px;font-size:17px}.bars{display:grid;gap:14px}.barLine{display:grid;grid-template-columns:105px 1fr 68px;align-items:center;gap:10px;font-size:12px}.barTrack{height:12px;background:#f0ebe8;border-radius:99px;overflow:hidden}.barFill{height:100%;border-radius:99px}.donutWrap{display:flex;align-items:center;justify-content:center;gap:24px;min-height:220px}.donut{width:170px;height:170px;border-radius:50%;position:relative}.donut:after{content:'';position:absolute;inset:35px;background:#fff;border-radius:50%}.donutCenter{position:absolute;inset:0;display:grid;place-content:center;text-align:center;z-index:2}.donutCenter b{font-size:25px}.legend{display:grid;gap:10px}.legend div{display:flex;align-items:center;gap:8px;font-size:12px}.dot{width:10px;height:10px;border-radius:50%}.moneyBreak{display:grid;gap:9px;margin-top:12px}.moneyBreak div{display:flex;justify-content:space-between;gap:10px;font-size:12px}.moneyBreak strong{direction:ltr}.proNote{margin-top:12px;padding:12px 14px;border-radius:13px;background:#fff8df;color:#76510a;font-size:12px}.proNote.ok{background:#eaf7ef;color:#245d3a}.proNote.bad{background:#fff0ee;color:#8b2d2d}.proLoading{padding:30px;text-align:center;color:#7b716d}@media(max-width:950px){.proHero{grid-template-columns:1fr}.proStats{grid-template-columns:repeat(2,1fr)}.proCharts{grid-template-columns:1fr}}@media(max-width:650px){.proStats{grid-template-columns:1fr 1fr}.proCard b{font-size:26px}.donutWrap{flex-direction:column}.barLine{grid-template-columns:80px 1fr 54px}}
`;document.head.appendChild(style);
const home=document.getElementById('home'),filters=home?.querySelector('.filters');if(!home||!filters)return;const box=document.createElement('div');box.id='proDashboard';box.className='proDash';box.innerHTML='<div class="proLoading">جاري تحميل الإحصائيات الموحّدة...</div>';filters.after(box);
const fmt=v=>Number(v||0).toLocaleString('fr-MA',{maximumFractionDigits:2});
async function auth(){const s=(await sb.auth.getSession()).data.session;if(!s)throw Error('LOGIN_REQUIRED');return s}
async function load(){try{const s=await auth(),q=new URLSearchParams({mode:'dashboard'});if(typeof dateFilter==='object'){if(dateFilter.from)q.set('from',dateFilter.from);if(dateFilter.to)q.set('to',dateFilter.to)}const r=await fetch(FN()+'?'+q,{headers:{authorization:'Bearer '+s.access_token}}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'OPS_API');render(j.stats)}catch(e){box.innerHTML=`<div class="msg err">تعذر تحميل الإحصائيات: ${String(e.message||e)}</div>`}}
function stat(n,v,sub,c){return `<div class="miniStat" style="--c:${c}"><span>${n}</span><b>${v}</b><em>${sub}</em></div>`}
function bar(n,v,total,c){const w=total?Math.max(v?2:0,v/total*100):0;return `<div class="barLine"><b>${n}</b><div class="barTrack"><div class="barFill" style="width:${w}%;background:${c}"></div></div><strong>${v}</strong></div>`}
function render(s){const total=Math.max(1,s.total_orders||0),closed=(s.delivered||0)+(s.refused||0)+(s.cancelled||0)+(s.plain_return||0)+(s.exchange||0),rate=Number(s.delivery_rate||0),green=Math.min(100,rate),yellow=Math.min(100,green+(s.in_progress||0)/Math.max(1,closed+(s.in_progress||0))*100);
const syncText=s.latest_sync_at?new Date(s.latest_sync_at).toLocaleString('fr-MA'):'Jamais';
const notes=[];if(s.stale_active)notes.push(`${s.stale_active} colis En cours ما تزامنوش من أكثر من 20 دقيقة`);if(s.missing_tariffs)notes.push(`${s.missing_tariffs} طلبية ما لقيناش لها tarif المدينة`);if(s.delivered_non_paye)notes.push(`${s.delivered_non_paye} Livré بحالة Non Payé خاصها مراجعة`);
box.innerHTML=`<div class="proHero"><div class="proCard pcDue"><small>Net à recevoir de Ozon</small><b>${fmt(s.net_due)} DH</b><small>${s.delivered_paye} Livré Payé</small><div class="moneyBreak"><div><span>COD Livré Payé</span><strong>${fmt(s.gross_due)} DH</strong></div><div><span>− Frais livraison</span><strong>${fmt(s.delivery_fees_due)} DH</strong></div><div><span>− Frais refus/retour à déduire</span><strong>${fmt(s.return_refuse_fees_due)} DH</strong></div></div></div><div class="proCard pcPaid"><small>Déjà facturé / réglé</small><b>${fmt(s.net_factured)} DH</b><small>${s.delivered_facture} commandes Livré Facturé</small><div class="moneyBreak"><div><span>COD facturé</span><strong>${fmt(s.gross_factured)} DH</strong></div><div><span>Frais livraison</span><strong>${fmt(s.delivery_fees_factured)} DH</strong></div><div><span>Frais retours/refus facturés</span><strong>${fmt(s.return_refuse_fees_factured)} DH</strong></div></div></div><div class="proCard pcCA"><small>Chiffre d'affaires COD total</small><b>${fmt(s.cod_total)} DH</b><small>${s.total_orders} commandes dans la période</small></div></div>
<div class="proStats">${stat('Livré',s.delivered,'Livraisons finales','#19764b')}${stat('En cours',s.in_progress,'Chez Ozon','#d59a24')}${stat('Livré Payé',s.delivered_paye,'Ozon doit encore nous régler','#3979b8')}${stat('Livré Facturé',s.delivered_facture,'Déjà réglé','#0c7b52')}${stat('Refusé',s.refused,'Inclut Refusé et retourné','#8e3434')}${stat('Annulé',s.cancelled,'Inclut Annulé et retourné','#7a4162')}${stat('Retour',s.plain_return,'Retour simple','#c54d4d')}${stat('Échange',s.exchange,'Livré puis retourné','#3979b8')}${stat('Non envoyé Ozon',s.not_sent,'Pas de Tracking','#6f625e')}${s.delivered_non_paye?stat('Livré Non Payé',s.delivered_non_paye,'À vérifier','#d16b20'):''}</div>
<div class="proCharts"><div class="chartCard"><h3>Statistiques colis</h3><div class="bars">${bar('Livré',s.delivered,total,'#15945c')}${bar('En cours',s.in_progress,total,'#d59a24')}${bar('Refusé',s.refused,total,'#8e3434')}${bar('Annulé',s.cancelled,total,'#7a4162')}${bar('Retour',s.plain_return,total,'#c54d4d')}${bar('Échange',s.exchange,total,'#3979b8')}</div></div><div class="chartCard"><h3>Taux de livraison</h3><div class="donutWrap"><div class="donut" style="background:conic-gradient(#15945c 0 ${green}%,#d59a24 ${green}% ${yellow}%,#c54d4d ${yellow}% 100%)"><div class="donutCenter"><b>${rate.toFixed(0)}%</b><small>Livré</small></div></div><div class="legend"><div><i class="dot" style="background:#15945c"></i>Livré: ${s.delivered}</div><div><i class="dot" style="background:#d59a24"></i>En cours: ${s.in_progress}</div><div><i class="dot" style="background:#c54d4d"></i>Incidents/retours: ${(s.refused||0)+(s.cancelled||0)+(s.plain_return||0)+(s.exchange||0)}</div></div></div></div></div><div class="proNote ${notes.length?'bad':'ok'}">${notes.length?notes.join(' · '):'Données centralisées et calculées côté serveur.'} · Dernière synchro Ozon: ${syncText}</div>`}
}
document.querySelectorAll('.period').forEach(b=>b.addEventListener('click',()=>setTimeout(load,250)));document.getElementById('applyDates')?.addEventListener('click',()=>setTimeout(load,250));document.querySelector('.nav[data-view="home"]')?.addEventListener('click',()=>setTimeout(load,100));window.EBRefreshProDashboard=load;setTimeout(load,500);setInterval(()=>{if(document.getElementById('home')?.classList.contains('active'))load()},5*60*1000);
})();