(()=>{
const OZON_CITIES='https://api.ozonexpress.ma/cities';
const style=document.createElement('style');style.textContent=`
#home .stats-grid{display:none!important}.proDash{margin-top:16px}.proHero{display:grid;grid-template-columns:1.2fr .9fr .9fr;gap:14px}.proCard{border-radius:22px;padding:22px;min-height:142px;position:relative;overflow:hidden;border:1px solid #e8e0db;box-shadow:0 12px 32px rgba(36,24,20,.08)}.proCard small{display:block;font-size:12px;opacity:.78}.proCard b{display:block;font-size:32px;margin:14px 0 5px;direction:ltr;text-align:right}.pcDue{background:linear-gradient(135deg,#ffd95a,#f2b934);color:#21180d}.pcPaid{background:linear-gradient(135deg,#092b25,#124e42);color:white}.pcCA{background:linear-gradient(135deg,#fdfdfc,#f0ece9);color:#201817}.proStats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:14px}.miniStat{background:#fff;border:1px solid #e9e2dd;border-radius:18px;padding:17px;box-shadow:0 7px 22px rgba(51,31,28,.05);border-top:4px solid var(--c)}.miniStat span{font-size:12px;color:#756a66}.miniStat b{display:block;font-size:27px;margin-top:7px}.miniStat em{display:block;font-style:normal;font-size:11px;color:#948985;margin-top:5px}.proCharts{display:grid;grid-template-columns:1.2fr .8fr;gap:14px;margin-top:14px}.chartCard{background:#fff;border:1px solid #e9e2dd;border-radius:20px;padding:20px;box-shadow:0 8px 24px rgba(51,31,28,.05)}.chartCard h3{margin:0 0 18px;font-size:17px}.bars{display:grid;gap:14px}.barLine{display:grid;grid-template-columns:105px 1fr 68px;align-items:center;gap:10px;font-size:12px}.barTrack{height:12px;background:#f0ebe8;border-radius:99px;overflow:hidden}.barFill{height:100%;border-radius:99px}.donutWrap{display:flex;align-items:center;justify-content:center;gap:24px;min-height:220px}.donut{width:170px;height:170px;border-radius:50%;position:relative}.donut:after{content:'';position:absolute;inset:35px;background:#fff;border-radius:50%}.donutCenter{position:absolute;inset:0;display:grid;place-content:center;text-align:center;z-index:2}.donutCenter b{font-size:25px}.legend{display:grid;gap:10px}.legend div{display:flex;align-items:center;gap:8px;font-size:12px}.dot{width:10px;height:10px;border-radius:50%}.moneyBreak{display:grid;gap:9px;margin-top:12px}.moneyBreak div{display:flex;justify-content:space-between;gap:10px;font-size:12px}.moneyBreak strong{direction:ltr}.proNote{margin-top:12px;padding:12px 14px;border-radius:13px;background:#fff8df;color:#76510a;font-size:12px}.proLoading{padding:30px;text-align:center;color:#7b716d}@media(max-width:950px){.proHero{grid-template-columns:1fr}.proStats{grid-template-columns:repeat(2,1fr)}.proCharts{grid-template-columns:1fr}}@media(max-width:650px){.proStats{grid-template-columns:1fr 1fr}.proCard b{font-size:26px}.donutWrap{flex-direction:column}.barLine{grid-template-columns:80px 1fr 54px}}
`;document.head.appendChild(style);
const home=document.getElementById('home'),filters=home?.querySelector('.filters');if(!home||!filters)return;const box=document.createElement('div');box.id='proDashboard';box.className='proDash';box.innerHTML='<div class="proLoading">جاري حساب الإحصائيات والتصفية المالية مع Ozon...</div>';filters.after(box);
const parcel=x=>Array.isArray(x?.ozon_parcels)?x.ozon_parcels[0]:(x?.ozon_parcels||null),num=v=>Number(String(v??0).replace(',','.').replace(/[^0-9.-]/g,''))||0,fmt=v=>num(v).toLocaleString('fr-MA',{maximumFractionDigits:2}),norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''),isDelivered=s=>norm(s).includes('livr')||norm(s).includes('deliver'),isReturn=s=>norm(s).includes('retour')||norm(s).includes('return'),isRefused=s=>norm(s).includes('refus'),isCancelled=s=>norm(s).includes('annul'),isFactured=s=>norm(s).includes('factur'),isPaye=s=>norm(s).includes('paye')||norm(s).includes('paid'),isProgress=s=>!isDelivered(s)&&!isReturn(s)&&!isRefused(s)&&!isCancelled(s);
async function allOrders(){let out=[],page=1,total=1;do{const j=await api(`orders?page=${page}&limit=100`);out.push(...(j.data||[]));total=Math.max(1,Math.ceil(Number(j.count||out.length)/100));page++}while(page<=total&&page<=100);return out}
function status(x){const p=parcel(x);return p?.ozon_status_label||p?.ozon_status||x.status||''}
function today(d){if(!d)return false;const a=new Date(d),b=new Date();return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
const key=s=>norm(s).replace(/[^a-z0-9]/g,''),pick=(o,names)=>{if(!o||typeof o!=='object')return null;const set=new Set(names.map(key));for(const [k,v] of Object.entries(o))if(set.has(key(k))&&v!==null&&v!==undefined&&v!=='')return v;return null};
function cityRecords(root){const out=[],seen=new Set();function walk(v,d=0){if(v==null||d>6)return;if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return}if(typeof v!=='object'||seen.has(v))return;seen.add(v);const name=pick(v,['CITY_NAME','city_name','name','ville','city','label']);const delivered=pick(v,['DELIVERED-PRICE','DELIVERED_PRICE','delivered_price','delivery_price','frais_livraison','livraison']);const refused=pick(v,['REFUSED-PRICE','REFUSED_PRICE','refused_price','return_price','RETURNED-PRICE','RETURNED_PRICE','returned_price','frais_refus','refus']);if(name&&(delivered!==null||refused!==null)){out.push(v);return}Object.values(v).forEach(x=>walk(x,d+1))}walk(root);return out}
async function tariffs(){let j;try{j=await fetch(EB.API+'/cities',{cache:'no-store'}).then(r=>r.json())}catch{j=await fetch(OZON_CITIES,{cache:'no-store'}).then(r=>r.json())}const arr=cityRecords(j?.data??j),map=new Map();arr.forEach(o=>{const n=pick(o,['CITY_NAME','city_name','name','ville','city','label']),d=pick(o,['DELIVERED-PRICE','DELIVERED_PRICE','delivered_price','delivery_price','frais_livraison','livraison']),r=pick(o,['REFUSED-PRICE','REFUSED_PRICE','refused_price','return_price','RETURNED-PRICE','RETURNED_PRICE','returned_price','frais_refus','refus']);if(n)map.set(norm(n).trim(),{delivered:num(d),refused:num(r)})});return map}
function feeFor(x,map,type){const t=map.get(norm(x.city_name).trim());if(!t)return 0;return type==='delivered'?t.delivered:t.refused}
function render(rows,tar){const sent=rows.filter(x=>parcel(x)?.tracking_number),del=sent.filter(x=>isDelivered(status(x))&&!isReturn(status(x))),ret=sent.filter(x=>isReturn(status(x))),ref=sent.filter(x=>isRefused(status(x))&&!isReturn(status(x))),ann=sent.filter(x=>isCancelled(status(x))&&!isReturn(status(x))),prog=sent.filter(x=>isProgress(status(x))),unsent=rows.filter(x=>!parcel(x)?.tracking_number);
const pendingDelivered=del.filter(x=>isPaye(status(x))&&!isFactured(status(x))),facturedDelivered=del.filter(x=>isFactured(status(x)));const grossDue=pendingDelivered.reduce((a,x)=>a+num(x.cod_total),0),deliveryFees=pendingDelivered.reduce((a,x)=>a+feeFor(x,tar,'delivered'),0),returnFees=[...ret,...ref,...ann].filter(x=>!isFactured(status(x))).reduce((a,x)=>a+feeFor(x,tar,'refused'),0),netDue=Math.max(0,grossDue-deliveryFees-returnFees),alreadyPaid=facturedDelivered.reduce((a,x)=>a+Math.max(0,num(x.cod_total)-feeFor(x,tar,'delivered')),0),totalCOD=rows.reduce((a,x)=>a+num(x.cod_total),0),todayCreated=rows.filter(x=>today(x.created_at)),todayDel=del.filter(x=>today(parcel(x)?.updated_at||parcel(x)?.status_updated_at||x.updated_at)),rate=sent.length?del.length/sent.length*100:0;const bad=ret.length+ref.length+ann.length,sum=Math.max(1,del.length+prog.length+bad),p1=del.length/sum*100,p2=p1+prog.length/sum*100;
box.innerHTML=`<div class="proHero"><div class="proCard pcDue"><small>Net estimé à recevoir de Ozon</small><b>${fmt(netDue)} DH</b><small>${pendingDelivered.length} Livré Payé غير Facturé</small><div class="moneyBreak"><div><span>COD brut en attente</span><strong>${fmt(grossDue)} DH</strong></div><div><span>− Frais livraison</span><strong>${fmt(deliveryFees)} DH</strong></div><div><span>− Frais refus/retour</span><strong>${fmt(returnFees)} DH</strong></div></div></div><div class="proCard pcPaid"><small>Déjà facturé / réglé par Ozon</small><b>${fmt(alreadyPaid)} DH</b><small>${facturedDelivered.length} commandes Livré Facturé</small></div><div class="proCard pcCA"><small>Chiffre d'affaires COD total</small><b>${fmt(totalCOD)} DH</b><small>${rows.length} commandes enregistrées</small></div></div>
<div class="proStats"><div class="miniStat" style="--c:#19764b"><span>Livré</span><b>${del.length}</b><em>${todayDel.length} livrées aujourd'hui</em></div><div class="miniStat" style="--c:#d59a24"><span>En cours</span><b>${prog.length}</b><em>Chez Ozon</em></div><div class="miniStat" style="--c:#3979b8"><span>Livré Payé</span><b>${pendingDelivered.length}</b><em>Pas encore facturé</em></div><div class="miniStat" style="--c:#0c7b52"><span>Livré Facturé</span><b>${facturedDelivered.length}</b><em>Déjà réglé</em></div><div class="miniStat" style="--c:#c54d4d"><span>Retourné</span><b>${ret.length}</b><em>À détailler dans Retours</em></div><div class="miniStat" style="--c:#8e3434"><span>Refusé</span><b>${ref.length}</b><em>Frais calculés selon ville</em></div><div class="miniStat" style="--c:#7a4162"><span>Annulé</span><b>${ann.length}</b><em>Frais calculés selon ville</em></div><div class="miniStat" style="--c:#5a4a9d"><span>Commandes aujourd'hui</span><b>${todayCreated.length}</b><em>${unsent.length} non envoyées à Ozon</em></div></div>
<div class="proCharts"><div class="chartCard"><h3>Statistiques colis</h3><div class="bars">${[['Livré',del.length,'#15945c'],['En cours',prog.length,'#d59a24'],['Retourné',ret.length,'#c54d4d'],['Refusé',ref.length,'#8e3434'],['Annulé',ann.length,'#7a4162'],['Non envoyé',unsent.length,'#7e6f68']].map(([n,v,c])=>`<div class="barLine"><b>${n}</b><div class="barTrack"><div class="barFill" style="width:${rows.length?Math.max(v?2:0,v/rows.length*100):0}%;background:${c}"></div></div><strong>${v}</strong></div>`).join('')}</div></div><div class="chartCard"><h3>Taux de livraison</h3><div class="donutWrap"><div class="donut" style="background:conic-gradient(#15945c 0 ${p1}%,#d59a24 ${p1}% ${p2}%,#c54d4d ${p2}% 100%)"><div class="donutCenter"><b>${rate.toFixed(0)}%</b><small>Livré</small></div></div><div class="legend"><div><i class="dot" style="background:#15945c"></i>Livré: ${del.length}</div><div><i class="dot" style="background:#d59a24"></i>En cours: ${prog.length}</div><div><i class="dot" style="background:#c54d4d"></i>Retour/Refus/Annulé: ${bad}</div></div></div></div></div><div class="proNote">Tarifs livraison/refus: synchronisés depuis l’API officielle Ozon Cities. “Livré Payé” = pas encore versé chez nous; “Livré Facturé” = déjà réglé.</div>`}
async function load(){try{const [rows,tar]=await Promise.all([allOrders(),tariffs()]);render(rows,tar)}catch(e){box.innerHTML=`<div class="msg err">تعذر تحميل الإحصائيات المتقدمة: ${String(e.message||e)}</div>`}}
setTimeout(load,300);document.querySelector('.nav[data-view="home"]')?.addEventListener('click',()=>setTimeout(load,120));window.EBRefreshProDashboard=load;
})();