(()=>{
  const FN=()=>`${EB.SUPABASE_URL}/functions/v1/ozon-delivery-notes`;
  const SEND=()=>`${EB.SUPABASE_URL}/functions/v1/ozon-send-order-v2`;
  let daily=[],notes=[];
  async function auth(){const s=(await sb.auth.getSession()).data.session;if(!s)throw Error('LOGIN_REQUIRED');return s}
  async function callDelivery(method='GET',body=null){const s=await auth(),r=await fetch(FN(),{method,headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||'DELIVERY_NOTE_API');return j}
  async function sendOrder(id){const s=await auth(),r=await fetch(SEND(),{method:'POST',headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json'},body:JSON.stringify({order_id:id})}),j=await r.json().catch(()=>({}));if(!r.ok||!j?.ok)throw Error(j?.error||('HTTP_'+r.status));return j}
  const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const parcel=x=>Array.isArray(x.ozon_parcels)?x.ozon_parcels[0]:(x.ozon_parcels||null),cust=x=>Array.isArray(x.customers)?x.customers[0]:(x.customers||{}),when=v=>{try{return new Date(v).toLocaleString('fr-MA',{dateStyle:'short',timeStyle:'short'})}catch{return v||''}};
  function sync(){const b=[...document.querySelectorAll('.bl-pick')],s=b.filter(x=>x.checked);blSelectedCount.textContent=s.length;blCreate.disabled=!s.length;blSelectAll.checked=b.length>0&&s.length===b.length;blSelectAll.indeterminate=s.length>0&&s.length<b.length}
  function render(){blReadyCount.textContent=daily.length;blReadyRows.innerHTML=daily.length?daily.map(x=>{const p=parcel(x),c=cust(x),sent=!!p?.tracking_number;return `<tr><td><input class="bl-pick" type="checkbox" value="${e(x.id)}" checked></td><td><b>${e(x.order_number||'—')}</b></td><td>${sent?`<span class="status good">Ozon ✓</span><br><small>${e(p.tracking_number)}</small>`:'<span class="status move">جاهزة للإرسال</span>'}</td><td>${e(c.name||'—')}<br><small>${e(c.phone_normalized||'')}</small></td><td>${e(x.city_name||'')}</td><td>${Number(x.cod_total||0).toFixed(2)} DH</td><td>${e(when(x.created_at))}</td></tr>`}).join(''):'<tr><td colspan="7">ما كايناش طلبات اليوم دابا.</td></tr>';sync()}
  function renderHistory(){blHistory.innerHTML=notes.length?notes.map(n=>`<div class="bl-note"><div><b>BL ${e(n.ref)}</b><small>${e(when(n.created_at))} · ${Number(n.parcel_count||0)} colis</small></div><div class="bl-links"><a href="${e(n.pdf_url)}" target="_blank" rel="noopener">PDF BL</a><a href="${e(n.tickets_a4_url)}" target="_blank" rel="noopener">Étiquettes A4</a><a href="${e(n.tickets_10x10_url)}" target="_blank" rel="noopener">Tickets 10×10</a></div></div>`).join(''):'مازال ما تخلق حتى Bon de Livraison من السيستيم.'}
  async function load(){blReadyRows.innerHTML='<tr><td colspan="7">جاري تحميل طلبات اليوم...</td></tr>';blMsg.textContent='';try{const d=new Date(),from=new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString(),to=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).toISOString(),q=new URLSearchParams({page:'1',limit:'100',from,to}),j=await api('orders?'+q);daily=(j.data||[]).filter(x=>!parcel(x)?.delivery_note_ref);render();try{const h=await callDelivery();notes=h.notes||[];renderHistory()}catch{blHistory.textContent='Historique BL غير متوفر مؤقتاً.'}}catch(err){blReadyRows.innerHTML=`<tr><td colspan="7">تعذر التحميل: ${e(err.message)}</td></tr>`}}
  async function create(){const ids=[...document.querySelectorAll('.bl-pick:checked')].map(x=>x.value);if(!ids.length)return;if(!confirm(`غادي نصيفط ${ids.length} طلبية مختارة لـ Ozon، ومن بعد نخلق Bon de Livraison واحد. نكمل؟`))return;blCreate.disabled=true;blCreate.textContent='Envoi à Ozon...';blMsg.className='msg';const tracks=[];let done=0;try{for(const id of ids){const x=daily.find(o=>String(o.id)===String(id)),p=parcel(x);let tr=p?.tracking_number;if(!tr){blMsg.textContent=`إرسال الطلبية ${done+1}/${ids.length} إلى Ozon...`;const r=await sendOrder(id);tr=r.tracking_number}if(!tr)throw Error('Tracking manquant après envoi Ozon');tracks.push(tr);done++}blCreate.textContent='Création BL...';blMsg.textContent=`تم إرسال ${done} طلبية لـ Ozon. جاري إنشاء Bon de Livraison...`;const j=await callDelivery('POST',{action:'create',tracking_numbers:tracks});blMsg.className='msg ok';blMsg.innerHTML=`تمت العملية بنجاح: ${done} colis في Ozon و Bon de Livraison واحد.<br><b>Référence: ${e(j.ref)}</b><div class="bl-success-links"><a target="_blank" rel="noopener" href="${e(j.pdf_url)}">فتح PDF BL</a><a target="_blank" rel="noopener" href="${e(j.tickets_a4_url)}">Étiquettes A4</a><a target="_blank" rel="noopener" href="${e(j.tickets_10x10_url)}">Tickets 10×10</a></div>`;await load()}catch(err){blMsg.className='msg err';blMsg.textContent=`توقفت العملية بعد ${done}/${ids.length}: ${err.message||err}`}finally{blCreate.textContent='Envoyer à Ozon + Créer BL';sync()}}
  function install(){const nav=document.querySelector('[data-view="delivery"]');if(!nav)return;nav.onclick=()=>{go('delivery');pageTitle.textContent='Bon de Livraison';load()};blRefresh.onclick=load;blSelectAll.onchange=ev=>{document.querySelectorAll('.bl-pick').forEach(x=>x.checked=ev.target.checked);sync()};blReadyRows.addEventListener('change',ev=>{if(ev.target.classList.contains('bl-pick'))sync()});blCreate.textContent='Envoyer à Ozon + Créer BL';blCreate.onclick=create;const sub=document.querySelector('#delivery .bl-head .muted');if(sub)sub.textContent='طلبات اليوم: اختار الكل أو اللي بغيتي، نصيفطهم لـ Ozon ونخلق BL واحد';}
  const style=document.createElement('style');style.textContent='.bl-head,.bl-toolbar,.bl-note{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.bl-summary{display:grid;grid-template-columns:repeat(2,minmax(150px,220px));gap:12px;margin:18px 0}.bl-summary>div{background:#faf7f4;border:1px solid #eee2dd;border-radius:14px;padding:14px}.bl-summary span{display:block;color:#806f69;font-size:12px}.bl-summary b{font-size:24px}.bl-toolbar{margin:10px 0 14px}.bl-checkall{display:flex;gap:8px;align-items:center;font-weight:700}.bl-pick,#blSelectAll{width:18px;height:18px;accent-color:#321d1b}.bl-note{padding:14px 0;border-bottom:1px solid #eee2dd}.bl-note small{display:block;color:#80736f;margin-top:5px}.bl-links,.bl-success-links{display:flex;gap:8px;flex-wrap:wrap}.bl-links a,.bl-success-links a{background:#f1e9e5;color:#321d1b;border-radius:10px;padding:8px 11px;text-decoration:none;font-weight:700}.bl-success-links{margin-top:12px}.bl-table small{direction:ltr;display:inline-block}@media(max-width:720px){.bl-summary{grid-template-columns:1fr 1fr}.bl-table{min-width:900px}}';document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();