(()=>{
  const FN=()=>`${EB.SUPABASE_URL}/functions/v1/ozon-delivery-notes`,SEND=()=>`${EB.SUPABASE_URL}/functions/v1/ozon-send-order-v2`;let daily=[],notes=[];
  async function auth(){const s=(await sb.auth.getSession()).data.session;if(!s)throw Error('LOGIN_REQUIRED');return s}
  async function req(url,body){const s=await auth(),r=await fetch(url,{method:body?'POST':'GET',headers:{authorization:'Bearer '+s.access_token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw Error(j.error||('HTTP_'+r.status));return j}
  const callDelivery=(method='GET',body=null)=>req(FN(),method==='GET'?null:body),sendOrder=id=>req(SEND(),{order_id:id});
  const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),parcel=x=>Array.isArray(x?.ozon_parcels)?x.ozon_parcels[0]:(x?.ozon_parcels||null),cust=x=>Array.isArray(x?.customers)?x.customers[0]:(x?.customers||{}),when=v=>{try{return new Date(v).toLocaleString('fr-MA',{dateStyle:'short',timeStyle:'short'})}catch{return v||''}};
  function sync(){const b=[...document.querySelectorAll('.bl-pick')],s=b.filter(x=>x.checked);blSelectedCount.textContent=s.length;blCreate.disabled=!s.length;blSelectAll.checked=b.length>0&&s.length===b.length;blSelectAll.indeterminate=s.length>0&&s.length<b.length}
  function render(){blReadyCount.textContent=daily.length;blReadyRows.innerHTML=daily.length?daily.map(x=>{const p=parcel(x),c=cust(x),sent=!!p?.tracking_number;return `<tr data-order="${e(x.id)}"><td><input class="bl-pick" type="checkbox" value="${e(x.id)}" checked></td><td><b>${e(x.order_number||'—')}</b></td><td class="bl-state">${sent?`<span class="status good">Ozon ✓</span><br><small>${e(p.tracking_number)}</small>`:'<span class="status move">جاهزة للإرسال</span>'}</td><td>${e(c.name||'—')}<br><small>${e(c.phone_normalized||'')}</small></td><td>${e(x.city_name||'')}</td><td>${Number(x.cod_total||0).toFixed(2)} DH</td><td>${e(when(x.created_at))}</td></tr>`}).join(''):'<tr><td colspan="7">ما كايناش طلبات اليوم دابا.</td></tr>';sync()}
  function renderHistory(){blHistory.innerHTML=notes.length?notes.map(n=>`<div class="bl-note"><div><b>BL ${e(n.ref)}</b><small>${e(when(n.created_at))} · ${Number(n.parcel_count||0)} colis</small></div><div class="bl-links"><a href="${e(n.pdf_url)}" target="_blank" rel="noopener">PDF BL</a><a href="${e(n.tickets_a4_url)}" target="_blank" rel="noopener">Étiquettes A4</a><a href="${e(n.tickets_10x10_url)}" target="_blank" rel="noopener">Tickets 10×10</a></div></div>`).join(''):'مازال ما تخلق حتى Bon de Livraison من السيستيم.'}
  async function load(){blReadyRows.innerHTML='<tr><td colspan="7">جاري تحميل طلبات اليوم...</td></tr>';blMsg.textContent='';try{const d=new Date(),from=new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString(),to=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).toISOString(),q=new URLSearchParams({page:'1',limit:'100',from,to}),j=await api('orders?'+q);daily=(j.data||[]).filter(x=>!parcel(x)?.delivery_note_ref);render();try{const h=await callDelivery();notes=h.notes||[];renderHistory()}catch{blHistory.textContent='Historique BL غير متوفر مؤقتاً.'}}catch(err){blReadyRows.innerHTML=`<tr><td colspan="7">تعذر التحميل: ${e(err.message)}</td></tr>`}}
  function niceError(err){const s=String(err?.message||err||'');if(s.includes('Invalid address length'))return 'العنوان قصير أو غير مقبول عند Ozon';if(s.includes('CITY'))return 'المدينة غير مربوطة بشكل صحيح مع Ozon';if(s.includes('PHONE'))return 'رقم الهاتف غير مقبول';return s.slice(0,220)}
  async function create(){const ids=[...document.querySelectorAll('.bl-pick:checked')].map(x=>x.value);if(!ids.length)return;if(!confirm(`غادي نفحص ونصيفط ${ids.length} طلبية لـ Ozon. الطلبية اللي فيها مشكل ما غاديش توقف الباقي. ومن بعد نخلق BL للناجحين. نكمل؟`))return;blCreate.disabled=true;blCreate.textContent='Envoi à Ozon...';blMsg.className='msg';const tracks=[],failed=[];let processed=0;
    for(const id of ids){const x=daily.find(o=>String(o.id)===String(id)),row=document.querySelector(`tr[data-order="${CSS.escape(String(id))}"]`),state=row?.querySelector('.bl-state');try{let tr=parcel(x)?.tracking_number;if(!tr){blMsg.textContent=`معالجة ${processed+1}/${ids.length}: ${x?.order_number||''}`;const r=await sendOrder(id);tr=r.tracking_number}if(!tr)throw Error('Tracking manquant après envoi Ozon');tracks.push(tr);if(state)state.innerHTML=`<span class="status good">Ozon ✓</span><br><small>${e(tr)}</small>`}catch(err){const reason=niceError(err);failed.push({order:x?.order_number||id,reason});if(state)state.innerHTML=`<span class="status bad">مشكلة</span><br><small class="bl-error">${e(reason)}</small>`}processed++}
    if(!tracks.length){blMsg.className='msg err';blMsg.innerHTML=`ما تصيفطات حتى طلبية لـ Ozon.<br>${failed.map(f=>`<b>${e(f.order)}</b>: ${e(f.reason)}`).join('<br>')}`;blCreate.textContent='Envoyer à Ozon + Créer BL';sync();return}
    try{blCreate.textContent='Création BL...';blMsg.textContent=`نجحو ${tracks.length}/${ids.length}. جاري إنشاء Bon de Livraison للناجحين...`;const j=await callDelivery('POST',{action:'create',tracking_numbers:tracks});blMsg.className=failed.length?'msg warn':'msg ok';blMsg.innerHTML=`تم إنشاء Bon de Livraison للطلبات الناجحة.<br><b>Référence: ${e(j.ref)}</b> · ${tracks.length} colis<div class="bl-success-links"><a target="_blank" rel="noopener" href="${e(j.pdf_url)}">فتح PDF BL</a><a target="_blank" rel="noopener" href="${e(j.tickets_a4_url)}">Étiquettes A4</a><a target="_blank" rel="noopener" href="${e(j.tickets_10x10_url)}">Tickets 10×10</a></div>${failed.length?`<div class="bl-failed"><b>${failed.length} طلبية ما دخلوش فـBL:</b><br>${failed.map(f=>`${e(f.order)} — ${e(f.reason)}`).join('<br>')}</div>`:''}`;setTimeout(load,1200)}catch(err){blMsg.className='msg err';blMsg.textContent=`الطلبات الناجحة فـOzon: ${tracks.length}. ولكن إنشاء BL فشل: ${niceError(err)}`}finally{blCreate.textContent='Envoyer à Ozon + Créer BL';sync()}}
  function install(){const nav=document.querySelector('[data-view="delivery"]');if(!nav)return;nav.onclick=()=>{go('delivery');pageTitle.textContent='Bon de Livraison';load()};blRefresh.onclick=load;blSelectAll.onchange=ev=>{document.querySelectorAll('.bl-pick').forEach(x=>x.checked=ev.target.checked);sync()};blReadyRows.addEventListener('change',ev=>{if(ev.target.classList.contains('bl-pick'))sync()});blCreate.textContent='Envoyer à Ozon + Créer BL';blCreate.onclick=create;const sub=document.querySelector('#delivery .bl-head .muted');if(sub)sub.textContent='اختار طلبات اليوم؛ الطلبية اللي فيها مشكل ما كتوقفش الباقي';}
  const style=document.createElement('style');style.textContent='.bl-head,.bl-toolbar,.bl-note{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap}.bl-summary{display:grid;grid-template-columns:repeat(2,minmax(150px,220px));gap:12px;margin:18px 0}.bl-summary>div{background:#faf7f4;border:1px solid #eee2dd;border-radius:14px;padding:14px}.bl-summary span{display:block;color:#806f69;font-size:12px}.bl-summary b{font-size:24px}.bl-toolbar{margin:10px 0 14px}.bl-checkall{display:flex;gap:8px;align-items:center;font-weight:700}.bl-pick,#blSelectAll{width:18px;height:18px;accent-color:#321d1b}.bl-note{padding:14px 0;border-bottom:1px solid #eee2dd}.bl-note small{display:block;color:#80736f;margin-top:5px}.bl-links,.bl-success-links{display:flex;gap:8px;flex-wrap:wrap}.bl-links a,.bl-success-links a{background:#f1e9e5;color:#321d1b;border-radius:10px;padding:8px 11px;text-decoration:none;font-weight:700}.bl-success-links{margin-top:12px}.bl-failed{margin-top:14px;padding:12px;border-radius:12px;background:#fff1ed}.bl-error{color:#a02c2c;font-weight:700}.bl-table small{direction:ltr;display:inline-block}@media(max-width:720px){.bl-summary{grid-template-columns:1fr 1fr}.bl-table{min-width:900px}}';document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();