(()=>{
  const CACHE_KEY='eb_return_analysis_v4',CACHE_MS=10*60*1000,AUTO_MS=5*60*1000;let all=[],classified=[];
  const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pof=x=>Array.isArray(x?.ozon_parcels)?x.ozon_parcels[0]:(x?.ozon_parcels||null),cof=x=>Array.isArray(x?.customers)?x.customers[0]:(x?.customers||{}),txt=v=>String(v||'').toLowerCase(),isReturned=s=>txt(s).includes('retour'),isReceived=s=>txt(s).includes('retourn')&&txt(s).includes('reçu par client');
  function ensureUI(){const side=document.querySelector('.side'),main=document.querySelector('.main');if(side&&!document.querySelector('[data-view="returns"]')){const btn=document.createElement('button');btn.className='nav';btn.dataset.view='returns';btn.innerHTML='↩ <span>Retours</span>';side.insertBefore(btn,document.getElementById('logout'))}if(main&&!document.getElementById('returns')){const s=document.createElement('section');s.id='returns';s.className='view';s.innerHTML=`<div class="card"><div class="returns-head"><div><h2>Retours Ozon</h2><div id="returnsProgress" class="muted">Synchronisation automatique</div></div><button id="returnsRefresh" class="btn soft">تحديث</button></div><div class="returns-kpis"><div class="ret-kpi waiting"><span>باقي عند Ozon</span><b id="returnsAtOzon">0</b></div><div class="ret-kpi received"><span>خديناهم من Ozon</span><b id="returnsReceived">0</b></div><div class="ret-kpi exchange"><span>Échange</span><b id="returnsExchange">0</b></div><div class="ret-kpi refused"><span>Refusé et retourné</span><b id="returnsRefused">0</b></div><div class="ret-kpi cancelled"><span>Annulé et retourné</span><b id="returnsCancelled">0</b></div><div class="ret-kpi plain"><span>Retour</span><b id="returnsPlain">0</b></div></div><div class="order-table-wrap"><table class="order-table"><thead><tr><th>الطلب</th><th>الزبون</th><th>المدينة</th><th>COD</th><th>نوع الرجوع</th><th>وضعية الرجوع</th><th>Tracking</th><th></th></tr></thead><tbody id="returnsRows"><tr><td colspan="8">جاري التحميل...</td></tr></tbody></table></div></div>`;main.appendChild(s)}if(!document.getElementById('returnsStyle')){const st=document.createElement('style');st.id='returnsStyle';st.textContent='.returns-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.returns-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:16px 0}.ret-kpi{padding:16px;border-radius:16px;color:#fff}.ret-kpi span{font-size:12px;opacity:.9}.ret-kpi b{display:block;font-size:28px;margin-top:5px}.ret-kpi.waiting{background:#c88719}.ret-kpi.received{background:#2d8b57}.ret-kpi.exchange{background:#3979b8}.ret-kpi.refused{background:#b84d4d}.ret-kpi.cancelled{background:#873b62}.ret-kpi.plain{background:#6b5e58}@media(max-width:750px){.returns-kpis{grid-template-columns:1fr 1fr}}';document.head.appendChild(st)}}
  async function fetchAll(){let page=1,out=[];while(page<=30){const j=await api(`orders?page=${page}&limit=100`),rows=j.data||[];out.push(...rows);if(rows.length<100||out.length>=Number(j.count||out.length))break;page++}return out}
  async function hist(track){try{const r=await api('tracking-history',{tracking_number:track});const h=Array.isArray(r?.history)?r.history:[];return {ok:true,history:h}}catch{return {ok:false,history:[]}}}
  function labels(h){return h.map(e=>String(e.status_label||e.status_code||'')).filter(Boolean)}
  function classifyFrom(order,h=[]){const p=pof(order),current=String(p?.ozon_status_label||p?.ozon_status||order.status||''),ls=labels(h),joined=ls.join(' | ').toLowerCase(),received=isReceived(current)||ls.some(isReceived),hadDelivered=joined.includes('livr')||joined.includes('deliver'),hadRefused=joined.includes('refus'),hadCancelled=joined.includes('annul');let type='Retour';if(hadDelivered)type='Échange';else if(hadRefused)type='Refusé et retourné';else if(hadCancelled)type='Annulé et retourné';return {...order,_return:{type,received,current,history:ls,checkedAt:Date.now()}}}
  function readCache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'{"items":{}}')}catch{return {items:{}}}}
  function writeCache(items){try{localStorage.setItem(CACHE_KEY,JSON.stringify({at:Date.now(),items}))}catch{}}
  async function analyze(force=false,background=false){all=await fetchAll();const candidates=all.filter(x=>isReturned(pof(x)?.ozon_status_label||pof(x)?.ozon_status||x.status)),cache=readCache(),items=cache.items||{},next={},out=[];let checked=0,reused=0,kept=0;
    for(const x of candidates){const p=pof(x),tr=String(p?.tracking_number||''),current=String(p?.ozon_status_label||p?.ozon_status||x.status||''),old=tr?items[tr]:null,terminal=isReceived(current);let row;
      const fresh=old&&old.current===current&&(terminal||Date.now()-Number(old.checkedAt||0)<CACHE_MS);
      if(!force&&fresh){row={...x,_return:old};reused++}else{const hr=tr?await hist(tr):{ok:false,history:[]};if(!hr.ok&&old){row={...x,_return:{...old,current,checkedAt:Date.now()}};kept++}else if(hr.ok&&hr.history.length===0&&old&&old.type&&old.type!=='Retour'){row={...x,_return:{...old,current,checkedAt:Date.now()}};kept++}else{row=classifyFrom(x,hr.history);checked++}}
      if(tr)next[tr]=row._return;out.push(row);if(!background){const prog=document.getElementById('returnsProgress');if(prog)prog.textContent=`تحديث ${checked} · محفوظ ${reused} · محمي ${kept}`}}
    classified=out;writeCache(next);window.dispatchEvent(new CustomEvent('eb:return-analysis-updated',{detail:{rows:out}}));return {rows:out,checked,reused,kept}}
  function updateDashboard(rows,orders){if(!document.getElementById('home'))return;const ensure=(id,label,cls='')=>{if(document.getElementById(id))return;const grid=document.querySelector('#home .stats-grid');if(!grid)return;const d=document.createElement('div');d.className=`kpi ${cls}`;d.innerHTML=`<span>${label}</span><b id="${id}">—</b>`;grid.appendChild(d)};ensure('cancelledSmartCount','Annulé','bad-kpi');ensure('refusedSmartCount','Refusé','bad-kpi');ensure('exchangeSmartCount','Échange','warn-kpi');ensure('returnSmartCount','Retour','bad-kpi');const c={cancelled:0,refused:0,exchange:0,ret:0};rows.forEach(x=>{const t=x._return.type;if(t==='Échange')c.exchange++;else if(t==='Refusé et retourné')c.refused++;else if(t==='Annulé et retourné')c.cancelled++;else c.ret++});orders.forEach(x=>{const s=txt(pof(x)?.ozon_status_label||pof(x)?.ozon_status||x.status);if(!s.includes('retour')){if(s.includes('annul'))c.cancelled++;else if(s.includes('refus'))c.refused++}});document.getElementById('cancelledSmartCount').textContent=c.cancelled;document.getElementById('refusedSmartCount').textContent=c.refused;document.getElementById('exchangeSmartCount').textContent=c.exchange;document.getElementById('returnSmartCount').textContent=c.ret}
  function render(rows){const tbody=document.getElementById('returnsRows');if(!tbody)return;const atOzon=rows.filter(x=>!x._return.received).length,got=rows.length-atOzon,ex=rows.filter(x=>x._return.type==='Échange').length,rf=rows.filter(x=>x._return.type==='Refusé et retourné').length,an=rows.filter(x=>x._return.type==='Annulé et retourné').length,plain=rows.filter(x=>x._return.type==='Retour').length;returnsAtOzon.textContent=atOzon;returnsReceived.textContent=got;returnsExchange.textContent=ex;returnsRefused.textContent=rf;returnsCancelled.textContent=an;returnsPlain.textContent=plain;tbody.innerHTML=rows.length?rows.map(x=>{const p=pof(x),c=cof(x),r=x._return,status=r.received?'مستلم عندنا — Retourné Reçu par client':'باقي عند Ozon',cl=r.received?'good':'move';return `<tr><td><b>${esc2(x.order_number||'—')}</b></td><td>${esc2(c.name||'—')}<br><small>${esc2(c.phone_normalized||'')}</small></td><td>${esc2(x.city_name||'')}</td><td>${Number(x.cod_total||0).toFixed(2)} DH</td><td><span class="status ${r.type==='Échange'?'move':'bad'}">${esc2(r.type)}</span></td><td><span class="status ${cl}">${esc2(status)}</span></td><td><span class="tracking-code">${esc2(p?.tracking_number||'—')}</span></td><td>${p?.tracking_number?`<button class="btn soft ret-track" data-track="${esc2(p.tracking_number)}">Suivi</button>`:''}</td></tr>`}).join(''):'<tr><td colspan="8">ما كاين حتى Retour.</td></tr>';tbody.querySelectorAll('.ret-track').forEach(b=>b.onclick=()=>{go('orders');openTracking(b.dataset.track)})}
  async function loadReturns(force=false){const tbody=document.getElementById('returnsRows');if(tbody&&!classified.length)tbody.innerHTML='<tr><td colspan="8">جاري مزامنة retours...</td></tr>';const r=await analyze(force,false);render(r.rows);updateDashboard(r.rows,all);const p=document.getElementById('returnsProgress');if(p)p.textContent=`جاهز · ${r.checked} تبدلو/جدد · ${r.reused} محفوظين · ${r.kept} محميين`}
  async function autoSync(){try{const r=await analyze(false,true);updateDashboard(r.rows,all);if(document.getElementById('returns')?.classList.contains('active')){render(r.rows);const p=document.getElementById('returnsProgress');if(p)p.textContent=`مزامنة تلقائية · ${r.checked} تبدلو/جدد`}}catch{}}
  function install(){ensureUI();const nav=document.querySelector('[data-view="returns"]');if(nav)nav.onclick=()=>{go('returns');pageTitle.textContent='Retours';loadReturns(false)};document.getElementById('returnsRefresh')?.addEventListener('click',()=>loadReturns(true));setTimeout(autoSync,1200);setInterval(autoSync,AUTO_MS);if(location.hash==='#returns')setTimeout(()=>nav?.click(),50)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();